--- #YAML:1.0
name: Digest-SHA-PurePerl
version: 5.41
author:
  - Mark Shelor, mshelor@cpan.org
abstract: Perl implementation of SHA-1/224/256/384/512
license: perl
requires: {}
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Digest::SHA::PurePerl:
    file: PurePerl.pm
    version: 5.41
generated_by: Module::Build version 0.22
