--- #YAML:1.0
name: Digest-SHA-PurePerl
version: 0.01
author:
  - Mark Shelor, mshelor@comcast.net
abstract: Perl implementation of SHA-1/224/256
license: perl
requires: {}
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Digest::SHA::PurePerl:
    file: PurePerl.pm
    version: 0.01
generated_by: Module::Build version 0.22
