--- #YAML:1.0
name: Digest-SHA-PurePerl
version: 5.86
abstract: Perl implementation of SHA-1/224/256/384/512
license: perl
author:
  - Mark Shelor, mshelor@cpan.org
requires:
  FileHandle: 0
  perl: 5.003
provides:
  Digest::SHA::PurePerl:
    file: lib/Digest/SHA/PurePerl.pm
    version: 5.86
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: Mark Shelor
